# Generated by Django 5.1.1 on 2024-09-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TickData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("tick_price", models.FloatField()),
                ("volume", models.IntegerField()),
                ("open_interest", models.IntegerField()),
            ],
        ),
    ]
